"""create alloy_components table

Revision ID: 33abc3c03cf8
Revises: a2c59e6ea74f
Create Date: 2026-02-04 16:58:58.946391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33abc3c03cf8'
down_revision: Union[str, Sequence[str], None] = 'a2c59e6ea74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
