"""create alloys table

Revision ID: a2c59e6ea74f
Revises: 
Create Date: 2026-02-04 16:37:27.749477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c59e6ea74f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alloys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alloys_id'), 'alloys', ['id'], unique=False)
    op.create_index(op.f('ix_alloys_name'), 'alloys', ['name'], unique=True)
    op.create_index(op.f('ix_alloys_slug'), 'alloys', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alloys_slug'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_name'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_id'), table_name='alloys')
    op.drop_table('alloys')
    # ### end Alembic commands ###
